# Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel8"
  config.vm.box_version = "8.6.0"
  
  config.vm.provider "libvirt" do |libvirt|
    libvirt.driver = "kvm"
    libvirt.memory = 2048
    libvirt.cpus = 2
  end

  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    sudo yum install -y vim
  SHELL
end
